import {
  REINVESTMENT_STRATEGIES,
  DERIVED_STATUSES,
  type ReinvestmentStrategy,
} from "@/domain/investments/model/constants"
import {
  withSimulatedReinvestment,
  isFixedTermMaturingBetweenDates,
} from "@/domain/investments/calculations/investment-projections"
import { toDateString } from "@/domain/investments/calculations/dates"
import { getInvestmentEstimatedCurrentValueAtDate } from "@/domain/investments/calculations/investment-state"
import { getDerivedStatus } from "@/domain/investments/events/lifecycle-periods"
import type { Investment } from "@/domain/investments/model/types"

/**
 * Result shape of an individual investment projection strategy execution.
 */
export interface ProjectedAssetResult {
  /**
   * The projected raw investment entity (potentially simulated/altered).
   */
  projectedInvestment: Investment
  /**
   * Strategy-adjusted individual projected value shown in the breakdown table.
   */
  projectedValue: number
  /**
   * Cash generated by matured assets (retained in the portfolio total).
   */
  cashGenerated: number
  /**
   * Value excluded from the portfolio projection (e.g. strict strategy cliff).
   */
  excludedValue: number
}

/**
 * Strategy handler interface for individual investment projections.
 */
export interface ProjectionStrategyHandler {
  project(
    investment: Investment,
    baselineDate: Date,
    projectionDate: Date,
  ): ProjectedAssetResult
}

/**
 * Keep as Cash strategy:
 * Matured fixed-term CDs become finished (earning pace falls to 0), but their accumulated
 * balance is retained inside the portfolio as cash.
 */
export const keepAsCashStrategy: ProjectionStrategyHandler = {
  project: (investment, baselineDate, projectionDate) => {
    const baselineDateString = toDateString(baselineDate)
    const projectionDateString = toDateString(projectionDate)

    // CD matures during projection window: its value is retained as portfolio cash
    const isMatured = isFixedTermMaturingBetweenDates(
      investment,
      baselineDateString,
      projectionDateString,
    )

    const projectedValue = getInvestmentEstimatedCurrentValueAtDate(
      investment,
      projectionDate,
    )

    return {
      projectedInvestment: investment,
      projectedValue,
      cashGenerated: isMatured ? projectedValue : 0,
      excludedValue: 0,
    }
  },
}

/**
 * Reinvest strategy:
 * Matured fixed-term CDs automatically reinvest into simulated open-ended assets at the same interest rate.
 */
export const reinvestStrategy: ProjectionStrategyHandler = {
  project: (investment, baselineDate, projectionDate) => {
    const projectedInvestment = withSimulatedReinvestment(
      investment,
      projectionDate,
      baselineDate,
    )

    const projectedValue = getInvestmentEstimatedCurrentValueAtDate(
      projectedInvestment,
      projectionDate,
    )

    return {
      projectedInvestment,
      projectedValue,
      cashGenerated: 0,
      excludedValue: 0,
    }
  },
}

/**
 * Strict strategy:
 * Matured fixed-term CDs are fully excluded. Their projected value drops to 0 at maturity.
 */
export const strictStrategy: ProjectionStrategyHandler = {
  project: (investment, _baselineDate, projectionDate) => {
    const isFinished =
      getDerivedStatus(investment, projectionDate) === DERIVED_STATUSES.finished

    const projectedValue = getInvestmentEstimatedCurrentValueAtDate(
      investment,
      projectionDate,
    )

    return {
      projectedInvestment: investment,
      projectedValue: isFinished ? 0 : projectedValue,
      cashGenerated: 0,
      excludedValue: isFinished ? projectedValue : 0,
    }
  },
}

const STRATEGIES: Record<ReinvestmentStrategy, ProjectionStrategyHandler> = {
  [REINVESTMENT_STRATEGIES.keepAsCash]: keepAsCashStrategy,
  [REINVESTMENT_STRATEGIES.reinvest]: reinvestStrategy,
  [REINVESTMENT_STRATEGIES.strict]: strictStrategy,
}

/**
 * Resolves the strategy handler for the specified ReinvestmentStrategy.
 */
export function getProjectionStrategy(
  strategy: ReinvestmentStrategy,
): ProjectionStrategyHandler {
  const handler = STRATEGIES[strategy]
  if (!handler) {
    throw new Error(`Unsupported reinvestment strategy: ${strategy}`)
  }
  return handler
}

/**
 * Projects a single investment to a target date according to the selected reinvestment strategy.
 * Encapsulates the strategy-pattern resolution inside the calculations layer.
 */
export function projectInvestmentWithStrategy(
  investment: Investment,
  baselineDate: Date,
  projectionDate: Date,
  strategy: ReinvestmentStrategy,
): ProjectedAssetResult {
  return getProjectionStrategy(strategy).project(
    investment,
    baselineDate,
    projectionDate,
  )
}
