export const GLOBAL_INVESTMENT_SEARCH_ORB_SIZE = 40

export const GLOBAL_INVESTMENT_SEARCH_FINAL_GAP = 12

export const GLOBAL_INVESTMENT_SEARCH_EXPANDED_BAR_LEFT =
  GLOBAL_INVESTMENT_SEARCH_ORB_SIZE + GLOBAL_INVESTMENT_SEARCH_FINAL_GAP

export const GLOBAL_INVESTMENT_SEARCH_SPLIT_OVERSHOOT_LEFT =
  GLOBAL_INVESTMENT_SEARCH_EXPANDED_BAR_LEFT + 4

export const GLOBAL_INVESTMENT_SEARCH_BOUNCE_SCALE = 1.06

export const GLOBAL_INVESTMENT_SEARCH_SEPARATED_WIDTH =
  GLOBAL_INVESTMENT_SEARCH_ORB_SIZE +
  GLOBAL_INVESTMENT_SEARCH_FINAL_GAP +
  GLOBAL_INVESTMENT_SEARCH_ORB_SIZE

export const GLOBAL_INVESTMENT_SEARCH_MOTION = {
  easing: [0.22, 1, 0.36, 1] as const,
  companionDuration: 0.28,
  openDuration: 2.2,
  closeDuration: 1.6,
  phaseTimes: [0, 0.28, 0.48, 1],
}
