import type { Investment } from "@/domain/investments/types"
import {
  CURRENCIES,
  INVESTMENT_TYPES,
  PAYMENT_FREQUENCIES,
  REINVESTMENT_BEHAVIORS,
} from "@/domain/investments/constants"

export const sampleInvestments: Investment[] = [
  {
    id: "investment-nu-90",
    name: "Nu congelada 90 dias",
    institutionName: "Nu",
    type: INVESTMENT_TYPES.fixedTerm,
    originalAmount: 50000,
    annualRate: 14.25,
    currency: CURRENCIES.mxn,
    paymentFrequency: PAYMENT_FREQUENCIES.atMaturity,
    reinvestmentBehavior: REINVESTMENT_BEHAVIORS.toCash,
    startDate: "2026-05-03",
    endDate: "2026-08-01",
    notes: "Sample fixed-term SOFIPO-style investment.",
    createdAt: "2026-05-03T12:00:00.000Z",
    updatedAt: "2026-05-03T12:00:00.000Z",
  },
  {
    id: "investment-cetes-28",
    name: "CETES 28 dias",
    institutionName: "CETES Directo",
    type: INVESTMENT_TYPES.fixedTerm,
    originalAmount: 35000,
    annualRate: 10.15,
    currency: CURRENCIES.mxn,
    paymentFrequency: PAYMENT_FREQUENCIES.atMaturity,
    reinvestmentBehavior: REINVESTMENT_BEHAVIORS.toCash,
    startDate: "2026-05-03",
    endDate: "2026-05-31",
    createdAt: "2026-05-03T12:05:00.000Z",
    updatedAt: "2026-05-03T12:05:00.000Z",
  },
  {
    id: "investment-klar-flex",
    name: "Klar flexible",
    institutionName: "Klar",
    type: INVESTMENT_TYPES.openEnded,
    originalAmount: 25000,
    annualRate: 12,
    currency: CURRENCIES.mxn,
    paymentFrequency: PAYMENT_FREQUENCIES.daily,
    reinvestmentBehavior: REINVESTMENT_BEHAVIORS.automatic,
    startDate: "2026-05-03",
    notes: "Sample open-ended investment with automatic reinvestment.",
    createdAt: "2026-05-03T12:10:00.000Z",
    updatedAt: "2026-05-03T12:10:00.000Z",
  },
]
